<template>
  <v-footer color="primary darken-2" padless>
    <v-row justify="center" no-gutters>
      <v-btn
        href="https://cnpemcamp.sharepoint.com/sites/iot/SitePages/SIMAR-Soft.aspx"
        color="white"
        text
        rounded
        class="my-2"
      >
        wiki
      </v-btn>
      <v-btn
        href="https://github.com/cnpem-iot/simar-frontend"
        color="white"
        text
        rounded
        class="my-2"
      >
        git
      </v-btn>
      <v-btn
        href="mailto:sei@cnpem.br"
        color="white"
        text
        rounded
        class="my-2"
      >
        contact
      </v-btn>
    </v-row>
  </v-footer>
</template>
