<template>
  <v-footer color="primary darken-2" padless>
    <v-row justify="center" no-gutters>
      <v-btn
        href="https://cnpemcamp.sharepoint.com/sites/iot/SitePages/SIMAR-Soft.aspx"
        color="white"
        text
        rounded
        class="my-2"
      >
        wiki
      </v-btn>
      <v-btn
        href="https://gitlab.cnpem.br/IoT/simar-vue"
        color="white"
        text
        rounded
        class="my-2"
      >
        gitlab
      </v-btn>
      <v-btn
        href="mailto:guilherme.freitas@cnpem.br"
        color="white"
        text
        rounded
        class="my-2"
      >
        contact
      </v-btn>
    </v-row>
  </v-footer>
</template>
